version: '3.4'

services:
  api:
    image: rekyuu/homuraapi:${HOMURA_API_VERSION}
    build:
      context: .
      dockerfile: src/HomuraApi/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      -  ./data:/data
    env_file:
      - secrets.env

  watcher:
    image: rekyuu/homurawatcher:${HOMURA_API_VERSION}
    build:
      context: .
      dockerfile: src/HomuraWatcher/Dockerfile
    volumes:
      -  ./data:/data
    env_file:
      - secrets.env
    depends_on:
      - api